### ISSUE TITLE
Database Not Being Checkpointed?

### ISSUE THREAD

**Issue by cwarden** [leijurv/gb#31]
It looks like the SQLite database isn't getting checkpointed during a run of `gb backup`.  

The WAL is growing to many times the ultimate size of the database, and the database isn't getting checkpointed until the backup completes.  During a long backup, the WAL grew for my database grew to 45GB; the database ended up being about 5GB.

**Comment by leijurv** [comment]
might help: https://github.com/leijurv/gb/commit/2c8df3ebec1d0a86f0021394ed02cdf8ffa93d6e

I ran a simple test where I repeatedly insert an unlimited number of rows into `sizes`, and I saw the `.gb.db` growing while the `-wal` stayed constant size.

**Comment by leijurv** [comment]
Per https://github.com/leijurv/gb/commit/2c8df3ebec1d0a86f0021394ed02cdf8ffa93d6e#commitcomment-99243585

https://stackoverflow.com/questions/16547263/clarification-regarding-journal-size-limit-in-sqlite

I now believe that the issue is that a transaction is very long-lived. I think it's almost certainly `scannerThread` in `backup/scanner.go`, specifically in how `utils.WalkFiles` only uses one large transaction. I think starting a new transaction for every scanned file would be too slow (this is a vague recollection from 2019), so I guess I need to recreate the transaction periodically? (even though it's read-only)

**Comment by leijurv** [comment]
@cwarden please try with https://github.com/leijurv/gb/commit/7e72ab57ef055592272e39ce20c3617262b34bd7

**Comment by leijurv** [comment]
Now that the scanner transaction is closed every second, there should be no more SQL transactions that remain open for the entire duration of a backup. This should hopefully allow the WAL to be truncated, as the `PRAGMA` directs it to be.

**Comment by cwarden** [comment]
I'm not sure if it's related, but I got the "somehow something isn't being synchronized" panic on the first run with 305f56000049c1ca1fa1177e4af41099279a366a.

**Comment by leijurv** [comment]
oof, sorry again, try with https://github.com/leijurv/gb/commit/490a8053bf61453cc3c17a30ba15eb0684dfdb99

bug seems to have been introduced accidentally here: https://github.com/leijurv/gb/commit/ca6b0b030a3d1e498179409c4b9f56b0904a3d16#diff-7b8b15093cd777455c713b59054b2fa528b1879a817e1e3a927a89f241dba45aL264-R207

**Comment by cwarden** [comment]
Looking good now

**Comment by cwarden** [comment]
This might have introduced a race condition.  Just got the following panic with 67825d5ced11df2bbba8ce679fac23fe148a1f19.
```
2023/02/15 17:20:09 Committing and recreating scanner transaction to prevent WAL from growing too large
2023/02/15 17:20:10 Bytes written: 0
panic: sql: database is closed

goroutine 28 [running]:
github.com/leijurv/gb/backup.(*ScannerTransactionContext).Tx(0xac8e070)
        /home/cwarden/git/gb/backup/scanner.go:169 +0x169
github.com/leijurv/gb/backup.(*ScannerTransactionContext).Tx(0xac8e070)
        /home/cwarden/git/gb/backup/scanner.go:180 +0x13c
github.com/leijurv/gb/backup.scannerThread.func1({0xe08b440, 0x8e}, {0x8dbcdec, 0xe08d4d0})
        /home/cwarden/git/gb/backup/scanner.go:46 +0x7a
github.com/leijurv/gb/utils.WalkFiles.func1()
        /home/cwarden/git/gb/utils/utils.go:51 +0x97
created by github.com/leijurv/gb/utils.WalkFiles
        /home/cwarden/git/gb/utils/utils.go:49 +0xc0
```

**Comment by leijurv** [comment]
Hm, strange! I've just taken a quick look and I have no idea how that could happen, fascinating. Do you have the rest of the log perhaps? For example did it print `Closing database` before that? I think that's the only place where the database is closed. But in `main.go`, `backup.BackupDB` is only called after `backup.Backup` completes? Did it print `Scanner committing` beforehand?

I guess this could be caused if `utils.WalkFiles` returned async - meaning it returns before it was done scanning all the files. But I don't see how that can happen since it explicitly calls `<-done` before returning? Did you get `Scan processor signaling done` in your log?

**Comment by cwarden** [comment]
Sorry, I don't have the rest of the log.  I'll keep an eye out for it again.

While looking into this, I think I found a bug in `ScannerTransactionContext.Tx`.  It calls itself after calling `ScannerTransactionContext.Close`.  Under load, `select` could keep reading from the ticker, such that it keeps committing and beginning a transaction, and never actually return a `sql.Tx`.

**Comment by leijurv** [comment]
I think that is unlikely because the ticker only sends a tick on the channel once a second. Committing then reopening an empty transaction that hasn't written anything will certainly take less than that I think?

**Comment by leijurv** [comment]
nevertheless here you go https://github.com/leijurv/gb/commit/65c4006074767064cc26e7f2ceedbed761581263

**Comment by cwarden** [comment]
Ah, so maybe just one extra time through the cycle.  First commit could be slow so that next time through `ScannerTransactionContext.Tx`, it gets a tick, but the next commit/begin should be fast.  I think you're right.

**Comment by leijurv** [comment]
Yeah. And on top of which, the scanner that uses this tx is doing so read-only, so even the first commit should be fast. Better safe than sorry though I'll leave that last commit in.
